### ISSUE TITLE
Display scroll bar when required

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1133]
#### Nature of issue?

- New feature request

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/62892339-accd6800-bd65-11e9-9631-0a722c660b74.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:

Display Scroll bar only when it's required!

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting! i think this is from the following style:
```scss
.sketches-table-container {
    overflow-y: scroll;
}
.asset-table-container {
    overflow-y: scroll;
}
```
which i think should be changed to `overflow-y: auto`
