### ISSUE TITLE
Ability to override the image-rendering, width, height attributes of the canvas

### ISSUE THREAD

**Issue by phrozen** [processing/p5.js-web-editor#1782]
#### Nature of issue?
- New feature request

#### New feature details:

Documentation of the property: [image-rendering](https://developer.mozilla.org/es/docs/Web/CSS/image-rendering)
Add the ability to set the `image-rendering` attribute of the canvas so that supported browsers (all modern browsers do). So that users can use `image-rendering: pixelated;` for example for the rendering canvas.

When using p5js on my site or own code, I can set the CSS properties myself by selecting the `.p5Canvas` class and overwriting the defaults. But I can't do that on the web editor or while embedding from the editor. Being able to set `image-rendering: pixelated;` in supported browsers is very useful for scaling pixelated graphics like 8-bit retro games.

What I currently do while embedding p5js sketches is:

```css
.p5Canvas {
    display: block;
    width: 100% !important;
    max-width: 850px; // depending on content, useful for embedding
    height: auto !important;
    image-rendering: pixelated;
}
```

Then, if I create a sketch with `createCanvas(100, 100);` I will have a 100 x 100 canvas that scales with the content where it is embedded and can be dynamically resized, it's responsive, and thanks to `image-rendering: pixelated;` keeps the pixel perfect graphics without blurring, of course it can be set to auto to enable the browser scaling properties.

Being able to override the inline CSS properties of the canvas is very useful for having sketches being shown in full screen with a button, etc...

Another approach is removing the inline properties of the sketch or overriding them within the iframe by using the `seamless` property with the `sandbox`. There is probably a way to override that way, but having a simpler solution would be better. Thoughts?
